// <auto-generated />
namespace GetBuckets.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class hashsetlocationdbtest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hashsetlocationdbtest));
        
        string IMigrationMetadata.Id
        {
            get { return "202108022141134_hashset locationdb test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
